dependencies:
  java_agent_lib: /home/qyh/projects/FixFL/MethodCallGraphBuilder/target/MethodCallGraphBuilder-1.0.jar
  bug_exec: /home/qyh/DATASET/defects4j-2.0.1/framework/bin/defects4j
search_model:
  series: openai
  model: gpt-4o-2024-11-20
  api_key: sk-HgK8u1JLa9TIX8iS5vfiTRERJHCy92jAvBmOtBPFZ5Y3GTly
  base_url: https://www.dmxapi.cn/v1
  llm_args:
    temperature: 0.7
verify_model:
  series: openai
  model: gpt-4-turbo-2024-04-09
  api_key: sk-HgK8u1JLa9TIX8iS5vfiTRERJHCy92jAvBmOtBPFZ5Y3GTly
  base_url: https://www.dmxapi.cn/v1
  llm_args:
    temperature: 0.7
hyper:
  parallel_search: false
  debug_workers: 5
  search_workers: 5
  verify_workers: 5
  max_test_cases: 5
  debug_rounds: 3
